# Set specific API version
apiVersion: apps/v1

# Type of Kubernetes resource
kind: Deployment     

# Add information for container/pod
metadata:

  # Name of the Kubernetes resource
  name: karsajobs    

# Define specifications for container/pod   
spec:

  # Number of pods to run at any given time
  replicas: 1           

  # Manage pod only for specific label
  selector: 

    # Select specific label
    matchLabels:

      # This deployment applies to any Pods matching the specified label
      app: karsajobs 

  # This deployment will create a set of pods using the configurations in this template      
  template:             

    # Add information for container/pod
    metadata:

      # The labels that will be applied to all of the pods in this deployment
      labels:         

        # Define label name for container/pod    
        app: karsajobs 

    # Set specification for container/Pod
    spec:             

      # Define image details
      containers:

      # Set container/pod name
      - name: karsajobs

        # Get image from registry
        image: docker.io/agus3rdyoga/karsajobs:latest 

        # Set condition for getting image
        imagePullPolicy: IfNotPresent

        # Add variable to container/pod
        env:
        - name: APP_PORT
          value: "8080"
        - name: MONGO_HOST
          value: "mongodb"
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: mongo-creds
              key: MONGO_ROOT_USERNAME
        - name: MONGO_PASS
          valueFrom:
            secretKeyRef:
              name: mongo-creds
              key: MONGO_ROOT_PASSWORD

        # Define port mapping
        ports:

          # Should match the port number that the Go application listens on
          - containerPort: 8080  

        # To check the health of the Pod
        livenessProbe:           
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5