apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config-vol
              mountPath: /etc/prometheus
            - name: prometheus-vol
              mountPath: /var/lib/prometheus/
      volumes:
        - name: config-vol
          configMap:
            name: prometheus-config
            defaultMode: 420
        - name: prometheus-vol
          persistentVolumeClaim:
            claimName: prometheus-pvc